### ISSUE TITLE
Switch in encoder decoder names

### ISSUE THREAD

**Issue by mperiwal-kore** [oduerr/dl_tutorial#2]
In https://github.com/oduerr/dl_tutorial/blob/master/tensorflow/vae/vae_demo.ipynb, are encoder and decoder title being switched?

**Comment by oduerr** [comment]
You are right. According to Kingma https://arxiv.org/abs/1312.6114 
"In this paper we will therefore also refer to the recognition model qφ(z|x)
as a probabilistic encoder"

Thanks for pointing out!
