### ISSUE TITLE
scipy.misc.imsave causes error "module' object has no attribute imsave"

### ISSUE THREAD

**Issue by ProgramItUp** [oduerr/dl_tutorial#3]
Block [10] of the code is:
```sprite = images_to_sprite(imgs)
scipy.misc.imsave(os.path.join(LOG_DIR, 'sprite.png'), sprite)
```
It is returning the error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-77b0287eb4e3> in <module>()
      1 sprite = images_to_sprite(imgs)
----> 2 scipy.misc.imsave(os.path.join(LOG_DIR, 'sprite.png'), sprite)

AttributeError: 'module' object has no attribute 'imsave'
```
I tried adding the full library path in block [1]
`import scipy.misc`
but this did not help.

Suggestions?

**Comment by ProgramItUp** [comment]
From [http://stackoverflow.com/questions/30720760/how-to-install-scipy-misc-package](http://stackoverflow.com/questions/30720760/how-to-install-scipy-misc-package)
First install pillow, then scipy. Possibly reinstall scipy.

Fixed the problem for me.

**Comment by NicoYuCN** [comment]
"conda install pillow" solved my problem ~

**Comment by liuzc188** [comment]
I guess the pillow and scipy versions have problems. 
Install two version can be solved!
pip install Pillow==5.0.0
pip install scipy==1.0.1

换成这两个版本，我的问题解决了

**Comment by liuzc188** [comment]
I guess the pillow and scipy versions have problems.
Install two version can be solved!
pip install Pillow==5.0.0
pip install scipy==1.0.1
换成这两个版本，我的问题解决了
my env:  win10，TensorFlow-gpu

**Comment by manaskumarpradhan** [comment]
> I guess the pillow and scipy versions have problems.
> Install two version can be solved!
> pip install Pillow==5.0.0
> pip install scipy==1.0.1
> 换成这两个版本，我的问题解决了
> my env: win10，TensorFlow-gpu

This one helps, thank you

**Comment by ednasawe** [comment]
> I guess the pillow and scipy versions have problems.
> Install two version can be solved!
> pip install Pillow==5.0.0
> pip install scipy==1.0.1
> 换成这两个版本，我的问题解决了
> my env: win10，TensorFlow-gpu

Thank you, this one was very helpful.
